version: '3.8'

services:
  postgres:
    image: postgres:13
    container_name: postgres_db
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    ports:
      - "5432:5432"
    networks:
      - my_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U myuser -d mydb"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - postgres_data:/var/lib/postgresql/data


  backend:
    build:
      context: ./backend_rds
    container_name: backend_rds
    ports:
      - "8000:8000"
    environment:
      DB_NAME: mydb
      DB_USER: myuser
      DB_PASSWORD: mypassword
      DB_HOST: postgres
      DB_PORT: 5432
      CORS_ALLOWED_ORIGINS: "http://localhost:8000,http://127.0.0.1:8000"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - my_network

networks:
  my_network:
    driver: bridge

volumes:
  postgres_data:
